=== warning5/hwtx/hwtxframework-ioc/src/main/resources/hwtx-ioc.xsd
<?xml version="1.0"?>
<!-- <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> -->

<xsd:schema xmlns="http://www.hxtx.com/schema/MiniContainer"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.hwtx.org/schema/components"
	elementFormDefault="qualified" xmlns:Q1="http://www.hwtx.org/schema/components"
	xmlns:Q2="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="composite">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="component" minOccurs="0"
					maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:choice minOccurs="0"
							maxOccurs="unbounded">
							<xsd:element name="property" minOccurs="0"
								maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:choice>
										<xsd:element name="map"
											type="Q1:mapType" maxOccurs="1" minOccurs="0">
										</xsd:element>
										<xsd:element name="value"
											type="xsd:string" maxOccurs="1" minOccurs="0">
										</xsd:element>
									</xsd:choice>
									<xsd:attribute name="name"
										type="xsd:string" />
									<!-- <xsd:choice> -->
									<xsd:attribute name="value"
										type="xsd:string" use="optional" />
									<xsd:attribute name="ref"
										type="xsd:string" use="optional" />
									<!-- </xsd:choice> -->
								</xsd:complexType>
							</xsd:element>
						</xsd:choice>
						<xsd:attribute name="name" type="xsd:string" />
						<xsd:attribute name="class" type="xsd:string" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="component-scan"
					type="Q1:component-scanType" maxOccurs="unbounded" minOccurs="0">
				</xsd:element>
				<xsd:element name="property-placeholder"
					type="Q1:property-placeholderType" maxOccurs="unbounded" minOccurs="0">
				</xsd:element>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="mapType">
		<xsd:sequence>
			<xsd:element name="entry" type="Q1:entryType" maxOccurs="unbounded"
				minOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="entryType">
		<xsd:attribute name="key" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="value" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="value-ref" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="component-scanType">
		<xsd:attribute name="base-package" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="property-placeholderType">
		<xsd:attribute name="location" type="xsd:string"></xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== warning5/hwtx/hwtxframework-app/src/main/resources/ioc/shiro.xml
<?xml version="1.0" encoding="UTF-8"?>
<composite xmlns="http://www.hwtx.org/schema/components"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.hwtx.org/schema/components hwtx-ioc.xsd">
	
	<component name="shiroFilter" class="com.hwtx.config.ShiroFilterFactoryBean">
		<property name="securityManager" ref="securityManager" />
		<property name="loginUrl" value="${adminPath}/login" />
		<property name="successUrl" value="${adminPath}/" />
		<property name="filters">
            <map>
                <entry key="authc" value-ref="formAuthenticationFilter"/>
                <entry key="resource" value-ref="resourceAuthFilter"/>
            </map>
        </property>
		<property name="filterChainDefinitions">
			<value>
				/static/** = anon
				/userfiles/** = anon
				${adminPath}/login = authc
				${adminPath}/logout = logout
				${adminPath}/** = resource
		 	</value>
		</property>
	</component>
	
	<component name="securityManager" class="org.apache.shiro.web.mgt.DefaultWebSecurityManager">
		<property name="realm" ref="systemAuthorizingRealm" />
	 	<property name="cacheManager" ref="shiroCacheManager" />
	</component>
	
	<component name="shiroCacheManager" class="org.apache.shiro.cache.ehcache.EhCacheManager">
		<property name="cacheManager" ref="cacheManager"/>
	</component>
</composite>
